### ISSUE TITLE
Example AQuery Prompt Failing

### ISSUE THREAD

**Issue by dqian3** [sunyinqi0508/AQuery2#8]
Hi, so after getting the docker build to work (#7), I tried running the example given in the README. 

However, I get the following output at the AQuery prompt (running inside the docker container).

```
root@206a72a6f0ac:/AQuery2# python3 prompt.py 
rm: cannot remove 'server/pch.hpp.gch': No such file or directory
clang++-18 -x c++-header server/pch.hpp -fPIC --std=c++20 --stdlib=libstdc++ -march=native -Ofast -DNDEBUG -fno-stack-protector -fopenmp -DTHREADING -D__AQUERY_ITC_USE_SEMPH__  -I/usr/local/include/monetdb -I/usr/include/monetdb  -Ideps 
Thread pool started with 20 threads;
> Dbg: Getting col %2, type: monetdbe_str
**** WELCOME TO AQUERY++! ****
f moving_avg.a 
> xexec
Traceback (most recent call last):
  File "/AQuery2/prompt.py", line 786, in <module>
    prompt(state=state)
  File "/AQuery2/prompt.py", line 487, in prompt
    state.cxt = cxt = xengine.exec(state.stmts, cxt, keep, parser.parse)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/AQuery2/engine/__init__.py", line 29, in exec
    generate(s, cxt)
  File "/AQuery2/engine/__init__.py", line 19, in generate
    ast_node.types[k](None, ast, cxt)
  File "/AQuery2/engine/ast.py", line 83, in __init__
    super().__init__(parent, node, context)
  File "/AQuery2/engine/ast.py", line 29, in __init__
    self.consume(node)
  File "/AQuery2/engine/ast.py", line 273, in consume
    projection(self.parent, node, self.context, True, subq_type=self.subq_type)
  File "/AQuery2/engine/ast.py", line 83, in __init__
    super().__init__(parent, node, context)
  File "/AQuery2/engine/ast.py", line 29, in __init__
    self.consume(node)
  File "/AQuery2/engine/ast.py", line 438, in consume
    self.group_node.finalize(gb_cexprs, gb_vartable, gb_colnames, gb_types, gb_tovec)
  File "/AQuery2/engine/ast.py", line 871, in finalize
    self.dedicated_gb.finalize(cexprs, var_table, col_names, col_types, col_tovec)
  File "/AQuery2/engine/ast.py", line 704, in finalize
    self.arr_values = {self.group.keys}#'arrvals_' + base62uuid(3)
                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by dqian3** [comment]
Note, this is only on the main brach. The tag https://github.com/sunyinqi0508/AQuery2/releases/tag/0.4.8a seems to be working.
